# Generated by Django 3.2.1 on 2021-05-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'question like',
                'verbose_name_plural': 'question like list',
                'db_table': 'forum_likequestion',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', through='questions.LikeQuestion', to='account.User')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'question_list',
                'db_table': 'forum_question',
                'ordering': ['created_time'],
            },
        ),
        migrations.AddField(
            model_name='likequestion',
            name='question_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment list',
                'db_table': 'forum_comment',
                'ordering': ['question_number'],
            },
        ),
    ]
