# Generated by Django 3.2.1 on 2021-05-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='login_id'),
        ),
    ]
